workflows:
  react_native_workflow:
    name: React Native Workflow
    environment:
      vars:
        NODE_VERSION: 19.6.0 # Specify your Node.js version
        REACT_NATIVE_VERSION: 0.75.3 # Optional: React Native version for reference
      # xcode: 14.2 # Specify Xcode version for iOS builds
      # cocoapods: 1.12.0 # Specify CocoaPods version
      flutter: stable # Required for Detox testing with Flutter dependencies
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          yarn install # or npm install

      - name: Run tests
        script: |
          echo "Running tests..."
          yarn test # Adjust this command to match your testing setup

      - name: Build Android APK
        script: |
          echo "Building Android APK..."
          cd android
          ./gradlew assembleRelease
          cd ..

      # - name: Build iOS
      #   script: |
      #     echo "Building iOS app..."
      #     cd ios
      #     pod install
      #     xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourApp.xcarchive
      #     xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportOptionsPlist $PWD/exportOptions.plist -exportPath $PWD/build
      #     cd ..

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      # - ios/build/*.ipa

    publishing:
      email:
        recipients:
          - alvinecom2018@gmail.com
